### ISSUE TITLE
Feature request: default to Ok

### ISSUE THREAD

**Issue by cdeutsch** [getdock/pptr-mock-server#9]
What are your thoughts on adding an option to default all requests not matching a `mockRequest` to Ok/continue?

In my use case, I'm doing visual diffing of screenshots, and I just want to mock a couple specific API calls per test, not the whole app.

I'm looking for something more like [Cypress's fixture feature](https://docs.cypress.io/api/commands/fixture.html#Syntax), and so far your API is the easiest to use for mocking Puppeteer requests.

**Comment by ermakovich** [comment]
Thanks for reaching out. Sorry for not answering for a while, had some health issues.

We can add ability to provide custom handling for requests. Some kind of optional callback, which accepts request object and can execute custom logic on it. There will be 3 options in total for different scenarios:
- `onRequest` - to be executed for any unhandled request. By default requests are aborted.
- `onAppRequest` - to be executed for any unhandled app request, i.e. request matching `baseAppUrl` option.  By default requests are continued.
- `onApiRequest` - to be executed for any unhandled api request, i.e. request matching `baseApiUrl` option. By default requests are responded with `200 OK {}` for convenience.

Example:
```
const browser = await puppeteer.launch();
const page = await browser.newPage();
const baseAppUrl = 'http://localhost';
this.mockRequest = await mockServer.init(page, {
  baseAppUrl,
  baseApiUrl: baseAppUrl + '/api/',
  onApiRequest: request => request.continue()
});
```

In this example any unhandled api requests are continued instead of responding with `200 OK {}` (default logic).

Caution: when using such option you should understand, that app will perform much more work by sending real external requests and handling responses. Test will be slower and less isolated, you won't be able to run it without network connection.
